### ISSUE TITLE
platform.ListValidators method not found

### ISSUE THREAD

**Issue by giuseppefrancaviglia** [ava-labs/slopes#13]
Hi guys,
I'm using slopes (version 1.4.3) to interact with the network, there is an issue with the `platform.ListValidators` method.

This is the instruction in my code:
`let vals = await platform.listValidators();`

and this is the output I get:

```
Error:  Error: Error returned: {"jsonrpc":"2.0","error":{"code":-32000,"message":"rpc: can't find method \"platform.ListValidators\"","data":null},"id":1}
    at /Users/francaviglia/ava-examples/node_modules/slopes/typings/src/utils/types.js:111:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async test (/Users/francaviglia/ava-examples/for-cycle/for-cycle.js:239:12)
```

**Comment by danlaine** [comment]
@collincusce 
The API call was changed from `listValidators` to `getCurrentValidators`/`getPendingValidators`.
This change was made a while ago but I guess nobody realized til now that we didn't update `listValidators`

Apologies for not telling you then. (All recent API changes have been backward compatible.)

**Comment by collincusce** [comment]
Oh. Dang. I'll fix it. Gimme a bit.

**Comment by collincusce** [comment]
The entire platform chain has changed. I'll fix it today.
