### ISSUE TITLE
get UTXOs by assetId

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/slopes#2]
Currently in the documentation when issuing a transaction, it is suggested to collect UTXOs by `let utxos = await avm.getUTXOs(myAddresses);`. Although this works, it is not ideal to send all UTXOs of different assets, to a single transaction of a single asset. 

It would be nice to have a function such as `avm.getUTXOsByAssetId(assetId)` so that the user gets only the relevant UTXOs for the asset being transferred. An even better way would be `avm.getUTXOsByAssetId(assetId, amount)` so that only the minimum required number of UTXOs  are sent with the transaction.

**Comment by collincusce** [comment]
Explain this part:

"An even better way would be avm.getUTXOsByAssetId(assetId, amount) so that only the minimum required number of UTXOs are sent with the transaction."

The makeUnsignedTx() function does this already.

**Comment by collincusce** [comment]
Re-reading this, I'm pretty sure there's a fundamental misunderstanding here. I'll work with you directly to make sure. 

My concern is to make sure that you now that UTXOs contain one and only one output, that outputs contain one and only one assetid, and that Tx only spend outputs from other transaction (not entire past transactions).

**Comment by collincusce** [comment]
Ok I think we worked this out. The kitchen-sink approach to the library probably isn't the best, but I'm happy to re-assess that at a later time if this becomes too complicated for people to manage.
