### ISSUE TITLE
Undefined/null not handled on avm.getAllBalances() return

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/slopes#21]
Once the promise of avm.getAllBalances resolves, if result is null/undefined this line causes an error.

`TypeError: Cannot convert undefined or null to object`

https://github.com/ava-labs/slopes/blob/4527a4473c489c91aa4e96fc7fd32f0735e41e3f/src/apis/avm/api.ts#L490

**Comment by collincusce** [comment]
This was fixed and should be closed.
