### ISSUE TITLE
`/ext/health` endpoint missing

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/slopes#26]
Hello,

I noticed that `/ext/health` endpoint is missing in Slopes .

I'm using it for my small dashboard project and I would like to migrate all my calls via Slopes :)

Should I start a PR on this or was it left out intentionally ? 

By the way this endpoint is not documented, I'll open an issue over there as well :) 

Edit : Add an example of call / response : 

```curl
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"health.getLiveness"
}' -H 'content-type:application/json; http://localhost:9650/ext/health' 
```

```json
{
  "jsonrpc": "2.0",
  "result": {
    "checks": {
      "network.validators.heartbeat": {
        "message": {
          "heartbeat": 1590918823
        },
        "timestamp": "2020-05-31T09:54:36.733208646Z",
        "duration": 7434,
        "contiguousFailures": 0,
        "timeOfFirstFailure": null
      }
    },
    "healthy": true
  },
  "id": 1
}
```

**Comment by collincusce** [comment]
Thank you for pointing this out! We're happy to accept a PR, but I think you should collaborate in Discord with @cgcardona on this one as well. Let us know. 

Related: https://github.com/ava-labs/docs/issues/24

**Comment by collincusce** [comment]
Fixed with https://github.com/ava-labs/slopes/pull/30
