### ISSUE TITLE
Can't determine denomination in createVariableCapAsset

### ISSUE THREAD

**Issue by CeliktepeMurat** [ava-labs/slopes#31]
![image](https://user-images.githubusercontent.com/26026913/83938674-4d05e900-a7df-11ea-82b1-272bd6761cf6.png)

When I try to create VariableCapAsset, there is no way to determine denomination. So it creates with 0 denomation

![image](https://user-images.githubusercontent.com/26026913/83938703-850d2c00-a7df-11ea-8511-938bb66c598e.png)

**Comment by collincusce** [comment]
Fixed with https://github.com/ava-labs/slopes/pull/32
