### ISSUE TITLE
keystore importUser typo

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/slopes#35]
I noticed that there is a typo in the` Keystore/api.ts` , `importUser` function.
It leads to the creation of a user with "" as username in Gecko .

Here is the typo (PR open btw)

```typescript
    importUser = async (username:string, user:string, password:string):Promise<boolean> => {
        let params = {
            "usermame": username, <== HERE
            "user": user,
            "password": password
        };
        return this.callMethod("keystore.importUser", params).then((response:RequestResponseData) => {
            return response.data["result"]["success"];
        });
    }
````

I'll open an issue (and why not a PR, I want to practice Go :p ) in Gecko, because we should not be able to import an user with an empty username. (There is a specific check in the createUser flow that is missing in the importUser flow)

**Comment by collincusce** [comment]
Fixed with https://github.com/ava-labs/slopes/pull/36
