### ISSUE TITLE
PlatformAPI - Missing `importKey` / `exportKey`

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/slopes#37]
Unless am blind, Slopes does not implement those 2 calls for the Platform API :

`platform.exportKey`
`platform.importKey`

PR #38

**Comment by tbrunain** [comment]
Wait the doc says that those 2 calls exist , but looking in Gecko, seems like they are not present .

**Comment by tbrunain** [comment]
Ah present in Gecko 0.5.3 , I'll upgrade then :p

**Comment by cgcardona** [comment]
Closed in https://github.com/ava-labs/slopes/pull/38
